### ISSUE TITLE
Convert app to responsive app.

### ISSUE THREAD

**Issue by leibniz21c** [ndo04343/container-based-hadoop-distributed-system-log-analyzer#5]
# 1. What
We should make the following design responsive. 
The xd to flutter plugin provided by Adobe xd is difficult to respond to. 
We have to go through the process of refactoring your code.

Design prototype : https://xd.adobe.com/view/3b380aca-6f30-43ab-a408-53407a516034-6e6b/

# 2. Why
Our application runs not only in the tablet PC environment, but also in the desktop environment such as windows, mac, and linux. 
The minimum resolution was fixed at 1280 * 768 in the previous meeting, but it should be possible to increase the resolution. 
Making our app responsive is **inevitable.**

# 3. How(You guess)
Block provider pattern, and just coding it to convert to responsive app.

**Comment by rongga** [comment]
The xd to flutter plugin provided by Adobe xd uses the adobe_xd package.
In that, we can set Pin to responsive size. And this allows for easy configuration of reactive layouts.
